language: node_js
dist: trusty
node_js:
  - "8.16.0"

jdk:
  - openjdk8
services:
  - docker

addons:
  code_climate:
    repo_token: 205921b25cd059b92e7234ee98533a35f08c81c5debd68dad3e6d468258c0489
  hosts:
    - localhost.walmart.com

before_install:
  - java -version
  - wget http://mirrors.gigenet.com/apache/cassandra/3.11.7/apache-cassandra-3.11.7-bin.tar.gz && tar -xvzf apache-cassandra-3.11.7-bin.tar.gz
  - sudo sh ./apache-cassandra-3.11.7/bin/cassandra -R
  - sleep 20

script:
  - cd electrode-ota-mariadb-schema
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec ota-db /common/wait-for-it.sh -t 30 ota-db:3306
  - docker-compose logs
  - yarn test
  - docker-compose down
