language: node_js
node_js:
 - "6"
jdk:
  - oraclejdk7


addons:
  code_climate:
    repo_token: 205921b25cd059b92e7234ee98533a35f08c81c5debd68dad3e6d468258c0489
  hosts:
    - localhost.walmart.com
  mariadb: '10.3'

before_install:
  - java -version
  - wget https://www.dropbox.com/s/f86zyi3qmhqvfbp/apache-cassandra-3.9.tar.gz?dl=1 -O apache-cassandra-3.9.tar.gz && tar -xvzf apache-cassandra-3.9.tar.gz
  - sudo sh ./apache-cassandra-3.9/bin/cassandra -R
  - mysql -u root -e 'SET GLOBAL binlog_format=ROW;'
  - sleep 20
